---
# restart policy of the docker container
dmirror_restart_policy: always

dmirror_domain: localhost
dmirror_port: 5000

dmirror_home: "{{ ansible_user_dir }}/.ansible-data/thomass.docker-mirror"

dmirror_pki_countrycode: ""
dmirror_pki_state: ""
dmirror_pki_locality: ""
dmirror_pki_organization: ""
