---
dependencies:
  - role: de.iteratec.hh.common
  - role: de.iteratec.hh.docker
  - role: de.iteratec.hh.pki
    pki_home: "{{ dmirror_home }}"
    pki_password: "{{ dmirror_pki_password }}"
    pki_server_dns: "{{ dmirror_domain }}"
    pki_ca_country: "{{ dmirror_pki_countrycode }}"
    pki_ca_state: "{{ dmirror_pki_state }}"
    pki_ca_locality: "{{ dmirror_pki_locality }}"
    pki_ca_organization: "{{ dmirror_pki_organization }}"
    pki_server_extfile_content: "subjectAltName = IP:{{ dmirror_ip }}"
