- name: create ansible ci prelive user
  become: yes
  user:
    name: "{{ aci_prelive_user }}"
    createhome: yes
    state: present

- name: create subfolders for Vagrantfiles
  become: yes
  become_user: ansibleci
  file:
    path: "/home/{{ aci_prelive_user }}/aci_prelive/{{ item.name }}"
    state: directory
  with_items: "{{ aci_prelive_machines }}"

- name: create Vagrantfiles
  become: yes
  become_user: ansibleci
  template:
    src: Vagrantfile.j2
    dest: "/home/{{ aci_prelive_user }}/aci_prelive/{{ item.name }}/Vagrantfile"
  register: vagrantfiles
  with_items: "{{ aci_prelive_machines }}"

- name: start vagrant machines
  become: yes
  become_user: ansibleci
  command: vagrant up
  args:
    chdir: "/home/{{ aci_prelive_user }}/aci_prelive/{{ item.name }}"
  register: vagrantup
  changed_when: vagrantup.stdout.find('default{{':'}} Done.') != -1
  with_items: "{{ aci_prelive_machines }}"

- name: reload vagrant machines
  become: yes
  become_user: ansibleci
  command: vagrant reload
  args:
    chdir: "/home/{{ aci_prelive_user }}/aci_prelive/{{ item.name }}"
  when: (vagrantfiles.results|selectattr("item", "equalto", item)| map(attribute='changed') | first) == true and (vagrantup.results|selectattr("item", "equalto", item)| map(attribute='changed') | first) == false
  with_items: "{{ aci_prelive_machines }}"
