---
- name: setup AnsibleCI Agents
  hosts: agents
  vars_files:
    - /used_config/vault.yml
    - /used_config/aci.yml
    - /used_config/agents.yml
  vars:
    ansible_become_pass: "{{ ACIA_SUDO_PASSWORD }}"
  remote_user: "{{ acia_login_user }}"
  roles:
    - de.iteratec.hh.ansible-ci-agent
