---

- name: remove distribution package of virtualbox
  become: yes
  apt:
    name: virtualbox
    state: absent

- name: install dkms as prerequisite
  become: yes
  apt:
    name: dkms
    state: present

##  remove if dkms works fine
# - name: install kernel headers as prerequisites
#   become: yes
#   shell: "echo $LANG; apt-get install -y linux-headers-$(uname -r)"
#   environment:
#     LANG: en_US.UTF-8
#     LANGUAGE: en_US.UTF-8
#   register: result
#   changed_when: "'0 upgraded' not in result.stdout and '0 newly installed' not in result.stdout"

- name: add apt-key for ubuntu < 16.04
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  when: ansible_distribution_version | version_compare('16.04', '<')

- name: add apt-key for ubuntu >= 16.04
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  when: ansible_distribution_version | version_compare('16.04', '>=')

- name: add official repository to apt sources list
  become: yes
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present

- name: install virtualbox
  become: yes
  apt:
    name: virtualbox-5.0
    state: present
    update_cache: yes
